### ISSUE TITLE
Another tiny link

### ISSUE THREAD

**Issue by bramvanginneken** [MIDL-Conference/midl-website#7]
There is now a single openreview page to point to all MIDL pages: https://openreview.net/group?id=MIDL.io

We could a little logo link to this page next to the existing 4. I don’t know if you can find a nice icon for it. 

On the left of the logo line we could have a tiny midl logo, linking back to the home page, because we’ll get a few more subpages I guess, with board, code of conduct etc. Not totally necessary but visually and aesthetically nice.

**Comment by nlessmann** [comment]
Yes, difficult to find a good icon for openreview, a pitty that they don't have a logo themselves.

Maybe something like this:
* https://fontawesome.com/icons/book-open?style=solid
* https://fontawesome.com/icons/book-reader?style=solid

Was thinking that there could also be an envelope linked to the email address info@midl.io (which should become a general MIDL email address after the 2019 editions, the upcoming editions can better use something more specific like 2020@midl.io etc).

Have to try if the MIDL logo can be made so small, otherwise we could use a house symbol like on midl2018.netlify.com

**Comment by nlessmann** [comment]
Could look like this: https://deploy-preview-8--midl-io.netlify.com/
